### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by cuongvng** [datluu-dev/devc-assignments#1]
SQL Task 7: một lỗi nhỏ thôi.
`select count(*) - count(distinct city) resust from station`
**resust** ko phải là 1 cột trong bảng, nếu muốn dùng alias phải thêm `as` phía trước.
Very good extra tasks!

**Comment by sudo-datluu** [comment]
à vâng tại em quen k dùng as ở mấy câu sau nên quên mất ạ. Thanks anh.
